### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by b4d** [Bal1/rt622p#1]
Hi, first of all nice reverse engineering work here!

I am looking at the code and wondering how exactly have you got to the startFreq and steps? I can't figure it out.

Why do you increase the int at positions 4 and 5 in hex to freq?

If you have some time to explain that would be wonderful!

Best regards
Deni

**Comment by Bal1** [comment]
Hi Deni,
If you set figures lower than 63 in last 2 positions software shows you 400.000000 freq, but this is not correct (maybe some bug) and it need's to start from 6 and 3 at last positions, if you set in file 00 00 63 - you will have 400.424960 freq, if something lower, 00 00 60 - this be 400.000000, but this is not correct, just a simple trying and trying.

I increased every byte for understand what figure will be added and wrote this script :)
